version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_USER: rails
       MYSQL_PASSWORD: rails
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
